export const siteImages = {
  hero: "/images/volcanic-bottle.png",
  originMountCameroon: "/images/hero-origin.png",
  studioBottle: "/images/studio-reflection.png",
  marketLifestyle: "/images/hero-origin.png",
  nightRoutine: "/images/night-routine.png",
  barbershop: "/images/hair-texture-lifestyle.png",
  packingOrders: "/images/packing-orders.png",
  frontLabel: "/images/front-label.png",
  backLabel: "/images/back-label.png",
  facebookCover: "/images/facebook-cover.png",
  profileLogo: "/images/profile-logo.png",
  heroOrigin: "/images/hero-origin.png",
  studioReflection: "/images/studio-reflection.png",
  volcanicBottle: "/images/volcanic-bottle.png",
  hairTextureLifestyle: "/images/hair-texture-lifestyle.png",
  globalHeroReference: "/images/global-hero-reference.png",
  mountCameroonRiverBottle: "/images/mount-cameroon-river-bottle.png",
  postpartumShedding: "/images/hair-texture-lifestyle.png",
  riverBottleOrigin: "/images/mount-cameroon-river-bottle.png",
  ingredientCastorOil: "/images/ingredient-castor-oil.png",
  ingredientSheaOil: "/images/ingredient-shea-oil.png",
  ingredientCoconutOil: "/images/ingredient-coconut-oil.png",
  ingredientJojobaOil: "/images/ingredient-jojoba-oil.png",
  ingredientAvocadoOil: "/images/ingredient-avocado-oil.png",
  ingredientOliveOil: "/images/ingredient-olive-oil.png",
} as const;

export type SiteImageKey = keyof typeof siteImages;
