import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Award,
  Bell,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  CreditCard,
  Download,
  Eye,
  EyeOff,
  Gift,
  Heart,
  Home,
  LayoutGrid,
  LifeBuoy,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  Package,
  Palette,
  Pencil,
  Plus,
  Search,
  Settings,
  ShoppingBag,
  Sparkles,
  Star,
  Sun,
  Trash2,
  User,
  Wallet,
  X,
} from "lucide-react";

export const Icons = {
  alert: AlertCircle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  award: Award,
  bell: Bell,
  camera: Camera,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clipboardList: ClipboardList,
  creditCard: CreditCard,
  download: Download,
  edit: Pencil,
  eye: Eye,
  eyeOff: EyeOff,
  gift: Gift,
  grid: LayoutGrid,
  heart: Heart,
  home: Home,
  lifeBuoy: LifeBuoy,
  loader: Loader2,
  lock: Lock,
  logOut: LogOut,
  mail: Mail,
  mapPin: MapPin,
  menu: Menu,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  package: Package,
  palette: Palette,
  plus: Plus,
  search: Search,
  settings: Settings,
  shoppingBag: ShoppingBag,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  trash: Trash2,
  user: User,
  wallet: Wallet,
  x: X,
} as const;
