import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  Heart,
  Loader2,
  Lock,
  Mail,
  Menu,
  Minus,
  Package,
  Plus,
  Search,
  Settings,
  ShoppingBag,
  Sparkles,
  Star,
  User,
  X,
} from "lucide-react";

export const Icons = {
  alert: AlertCircle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  creditCard: CreditCard,
  heart: Heart,
  loader: Loader2,
  lock: Lock,
  mail: Mail,
  menu: Menu,
  minus: Minus,
  package: Package,
  plus: Plus,
  search: Search,
  settings: Settings,
  shoppingBag: ShoppingBag,
  sparkles: Sparkles,
  star: Star,
  user: User,
  x: X,
} as const;
